import React, { useState } from 'react';
import { useAccounting } from '../../context/AccountingContext';
import { JournalVoucher } from '../../types/accounting';
import { formatCurrency } from '../../utils/dateUtils';
import { VoucherModal } from './VoucherModal';
import { VoucherPrintModal } from './VoucherPrintModal';
import {
  FileSpreadsheet,
  Plus,
  Search,
  Printer,
  Edit2,
  Trash2,
  CheckCircle2,
  Clock,
  Cpu,
  Layers,
  ArrowUpDown
} from 'lucide-react';

export const JournalVouchersView: React.FC = () => {
  const { vouchers, deleteVoucher, settings } = useAccounting();

  const [filterType, setFilterType] = useState<'all' | 'manual' | 'auto'>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedVoucherForPrint, setSelectedVoucherForPrint] = useState<JournalVoucher | null>(null);
  const [selectedVoucherForEdit, setSelectedVoucherForEdit] = useState<JournalVoucher | null>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);

  const filteredVouchers = vouchers.filter((v) => {
    const matchType =
      filterType === 'all' ||
      (filterType === 'manual' && !v.isAutoGenerated) ||
      (filterType === 'auto' && v.isAutoGenerated);

    const matchSearch =
      searchQuery === '' ||
      v.voucherNumber.toString().includes(searchQuery) ||
      v.description.includes(searchQuery) ||
      v.items.some((i) => i.accountTitle.includes(searchQuery) || i.description.includes(searchQuery));

    return matchType && matchSearch;
  });

  const totalTurnover = vouchers.reduce(
    (sum, v) => sum + v.items.reduce((s, i) => s + i.debit, 0),
    0
  );

  const handleDelete = (id: string, num: number) => {
    if (window.confirm(`آیا از حذف سند حسابداری شماره ${num} اطمینان دارید؟`)) {
      deleteVoucher(id);
    }
  };

  return (
    <div className="space-y-5 animate-in fade-in duration-150">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <FileSpreadsheet className="w-5 h-5 text-emerald-600" />
            <span>اسناد حسابداری (دفتر روزنامه و سیستم دوبل)</span>
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            ثبت اسناد دستی دوبل، مشاهده و چاپ اسناد صادره اتوماتیک فاکتورها و هزینه‌ها
          </p>
        </div>

        <button
          onClick={() => {
            setSelectedVoucherForEdit(null);
            setShowCreateModal(true);
          }}
          id="btn-new-voucher"
          className="flex items-center gap-1.5 px-3.5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-md shadow-emerald-600/20 transition"
        >
          <Plus className="w-4 h-4" />
          <span>ثبت سند حسابداری جدید</span>
        </button>
      </div>

      {/* Metric Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-xs">
          <div className="text-[11px] text-slate-500 flex items-center justify-between">
            <span>تعداد کل اسناد مالی</span>
            <Layers className="w-4 h-4 text-slate-400" />
          </div>
          <div className="text-base font-bold text-slate-900 font-mono mt-1">
            {vouchers.length} سند
          </div>
        </div>

        <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-xs">
          <div className="text-[11px] text-slate-500 flex items-center justify-between">
            <span>اسناد ثبت دستی</span>
            <Edit2 className="w-4 h-4 text-emerald-500" />
          </div>
          <div className="text-base font-bold text-emerald-700 font-mono mt-1">
            {vouchers.filter((v) => !v.isAutoGenerated).length} سند
          </div>
        </div>

        <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-xs">
          <div className="text-[11px] text-slate-500 flex items-center justify-between">
            <span>اسناد اتوماتیک سیستم</span>
            <Cpu className="w-4 h-4 text-indigo-500" />
          </div>
          <div className="text-base font-bold text-indigo-700 font-mono mt-1">
            {vouchers.filter((v) => v.isAutoGenerated).length} سند
          </div>
        </div>

        <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-xs">
          <div className="text-[11px] text-slate-500 flex items-center justify-between">
            <span>گردش کل اسناد (بدهکار/بستانکار)</span>
            <ArrowUpDown className="w-4 h-4 text-blue-500" />
          </div>
          <div className="text-base font-bold text-slate-900 font-mono mt-1">
            {formatCurrency(totalTurnover, settings.currency)}
          </div>
        </div>
      </div>

      {/* Table & Controls */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-xs p-4 space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 border-b border-slate-100 pb-3">
          {/* Tabs */}
          <div className="flex flex-wrap gap-1.5">
            {[
              { id: 'all', label: 'همه اسناد', count: vouchers.length },
              { id: 'manual', label: 'اسناد دستی', count: vouchers.filter((v) => !v.isAutoGenerated).length },
              { id: 'auto', label: 'اسناد اتوماتیک', count: vouchers.filter((v) => v.isAutoGenerated).length },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setFilterType(tab.id as any)}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition ${
                  filterType === tab.id
                    ? 'bg-slate-900 text-white shadow-xs'
                    : 'text-slate-600 hover:bg-slate-100'
                }`}
              >
                <span>{tab.label}</span>
                <span className="mr-1.5 text-[10px] px-1.5 py-0.2 rounded-full bg-slate-200 text-slate-800">
                  {tab.count}
                </span>
              </button>
            ))}
          </div>

          {/* Search Box */}
          <div className="relative w-full md:w-72">
            <Search className="w-4 h-4 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="جستجو در شماره سند، شرح یا حساب..."
              className="w-full pl-3 pr-9 py-1.5 text-xs bg-slate-50 border border-slate-200 rounded-xl outline-hidden focus:bg-white focus:border-emerald-500"
            />
          </div>
        </div>

        {/* Vouchers Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-right text-xs">
            <thead className="bg-slate-50 text-slate-600 font-bold border-b border-slate-200">
              <tr>
                <th className="py-3 px-3 font-mono w-20">شماره</th>
                <th className="py-3 px-3 w-28">تاریخ سند</th>
                <th className="py-3 px-3 min-w-[280px]">شرح سند</th>
                <th className="py-3 px-3 w-28">نوع سند</th>
                <th className="py-3 px-3 text-left w-36">مبلغ سند ({settings.currency})</th>
                <th className="py-3 px-3 w-24 text-center">وضعیت</th>
                <th className="py-3 px-3 text-center w-28">عملیات</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredVouchers.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-8 text-center text-slate-400">
                    هیچ سندی با مشخصات مورد نظر یافت نشد.
                  </td>
                </tr>
              ) : (
                filteredVouchers.map((vch) => {
                  const voucherSum = vch.items.reduce((s, i) => s + i.debit, 0);

                  return (
                    <tr key={vch.id} className="hover:bg-slate-50/80 transition">
                      <td className="py-3 px-3 font-mono font-bold text-slate-900">
                        {vch.voucherNumber}
                      </td>
                      <td className="py-3 px-3 font-mono text-slate-500">{vch.date}</td>
                      <td className="py-3 px-3">
                        <div className="font-medium text-slate-800">{vch.description}</div>
                        <div className="text-[11px] text-slate-400 mt-0.5">
                          {vch.items.length} ردیف آرتیکل (
                          {vch.items.map((i) => i.accountTitle).slice(0, 2).join('، ')}
                          {vch.items.length > 2 ? ' ...' : ''})
                        </div>
                      </td>
                      <td className="py-3 px-3">
                        {vch.isAutoGenerated ? (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-indigo-50 text-indigo-700 border border-indigo-200">
                            <Cpu className="w-3 h-3" />
                            <span>سیستمی</span>
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                            <Edit2 className="w-3 h-3" />
                            <span>دستی</span>
                          </span>
                        )}
                      </td>
                      <td className="py-3 px-3 font-mono font-bold text-slate-900 text-left">
                        {formatCurrency(voucherSum, settings.currency)}
                      </td>
                      <td className="py-3 px-3 text-center">
                        {vch.status === 'permanent' ? (
                          <span className="text-[10px] px-2 py-0.5 bg-emerald-50 text-emerald-700 rounded-full font-medium">
                            قطعی
                          </span>
                        ) : (
                          <span className="text-[10px] px-2 py-0.5 bg-amber-50 text-amber-700 rounded-full font-medium">
                            پیش‌نویس
                          </span>
                        )}
                      </td>
                      <td className="py-3 px-3 text-center">
                        <div className="flex items-center justify-center gap-1">
                          <button
                            onClick={() => setSelectedVoucherForPrint(vch)}
                            title="چاپ سند دوبل"
                            className="p-1.5 text-slate-600 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg transition"
                          >
                            <Printer className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => {
                              setSelectedVoucherForEdit(vch);
                              setShowCreateModal(true);
                            }}
                            title="ویرایش سند"
                            className="p-1.5 text-slate-600 hover:text-amber-600 hover:bg-amber-50 rounded-lg transition"
                          >
                            <Edit2 className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => handleDelete(vch.id, vch.voucherNumber)}
                            title="حذف سند"
                            className="p-1.5 text-slate-600 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal for Create / Edit */}
      {showCreateModal && (
        <VoucherModal
          voucherToEdit={selectedVoucherForEdit}
          onClose={() => {
            setShowCreateModal(false);
            setSelectedVoucherForEdit(null);
          }}
        />
      )}

      {/* Official Voucher Print Modal */}
      {selectedVoucherForPrint && (
        <VoucherPrintModal
          voucher={selectedVoucherForPrint}
          onClose={() => setSelectedVoucherForPrint(null)}
        />
      )}
    </div>
  );
};
