import React from 'react';
import { JournalVoucher } from '../../types/accounting';
import { useAccounting } from '../../context/AccountingContext';
import { formatCurrency, numberToWordsPersian } from '../../utils/dateUtils';
import { Printer, X, FileSpreadsheet, Building2, CheckCircle2 } from 'lucide-react';

interface VoucherPrintModalProps {
  voucher: JournalVoucher;
  onClose: () => void;
}

export const VoucherPrintModal: React.FC<VoucherPrintModalProps> = ({ voucher, onClose }) => {
  const { settings } = useAccounting();

  const handlePrint = () => {
    window.print();
  };

  const totalDebit = voucher.items.reduce((sum, item) => sum + item.debit, 0);
  const totalCredit = voucher.items.reduce((sum, item) => sum + item.credit, 0);

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col border border-slate-200">
        {/* Top Control Bar */}
        <div className="no-print p-4 border-b border-slate-200 flex items-center justify-between bg-slate-50 rounded-t-2xl">
          <div className="flex items-center gap-2">
            <Printer className="w-5 h-5 text-emerald-600" />
            <h3 className="font-bold text-slate-800 text-sm">
              چاپ سند حسابداری دوبل شماره {voucher.voucherNumber}
            </h3>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              id="btn-trigger-print-voucher"
              className="flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-md transition"
            >
              <Printer className="w-4 h-4" />
              <span>چاپ سند</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-slate-200 text-slate-500 hover:text-slate-800 rounded-xl transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Area */}
        <div className="p-8 overflow-y-auto print-page font-sans text-slate-900">
          <div className="border-2 border-slate-800 p-5 rounded-lg space-y-4">
            {/* Header */}
            <div className="flex items-start justify-between border-b-2 border-slate-800 pb-3">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-slate-900 text-white rounded-lg flex items-center justify-center font-bold">
                  <Building2 className="w-7 h-7" />
                </div>
                <div>
                  <h2 className="text-base font-black text-slate-900">{settings.companyName}</h2>
                  <p className="text-[11px] text-slate-600">سیستم مکانیزه حسابداری مالی</p>
                </div>
              </div>

              <div className="text-center">
                <h1 className="text-lg font-black text-slate-900 tracking-wide border-b border-slate-400 pb-1">
                  سند حسابداری (دوبل)
                </h1>
                <span className="text-[10px] text-slate-500 font-medium">
                  {voucher.status === 'permanent' ? 'ثبت قطعی و نهایی' : 'پیش‌نویس / موقت'}
                </span>
              </div>

              <div className="text-left text-xs space-y-1 font-mono">
                <div>
                  <span className="text-slate-600 font-sans font-medium text-[11px]">شماره سند: </span>
                  <span className="font-bold text-slate-900">{voucher.voucherNumber}</span>
                </div>
                <div>
                  <span className="text-slate-600 font-sans font-medium text-[11px]">تاریخ سند: </span>
                  <span className="font-bold text-slate-900">{voucher.date}</span>
                </div>
                <div>
                  <span className="text-slate-600 font-sans font-medium text-[11px]">نوع سند: </span>
                  <span className="font-sans text-[11px] text-slate-700">
                    {voucher.isAutoGenerated ? 'سیستمی (اتوماتیک)' : 'دستی / عمومی'}
                  </span>
                </div>
              </div>
            </div>

            {/* General Description */}
            <div className="p-2.5 bg-slate-50 rounded border border-slate-300 text-xs">
              <span className="font-bold text-slate-800">شرح کلی سند: </span>
              <span className="text-slate-900 font-medium">{voucher.description}</span>
            </div>

            {/* Articles Table */}
            <div className="overflow-x-auto">
              <table className="w-full text-right text-xs border border-slate-300">
                <thead className="bg-slate-200 text-slate-800 font-bold border-b border-slate-300">
                  <tr>
                    <th className="py-2 px-2 border-l border-slate-300 w-8 text-center">ردیف</th>
                    <th className="py-2 px-3 border-l border-slate-300 w-24">کد حساب</th>
                    <th className="py-2 px-3 border-l border-slate-300 w-44">عنوان سرفصل حسابداری</th>
                    <th className="py-2 px-3 border-l border-slate-300 w-40">تفصیلی / مرکز</th>
                    <th className="py-2 px-3 border-l border-slate-300">شرح آرتیکل</th>
                    <th className="py-2 px-3 border-l border-slate-300 w-32 text-left">بدهکار ({settings.currency})</th>
                    <th className="py-2 px-3 text-left w-32">بستانکار ({settings.currency})</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200">
                  {voucher.items.map((item, idx) => (
                    <tr key={item.id} className="hover:bg-slate-50">
                      <td className="py-2 px-2 border-l border-slate-200 text-center font-mono">{idx + 1}</td>
                      <td className="py-2 px-3 border-l border-slate-200 font-mono font-bold text-slate-700">
                        {item.accountCode}
                      </td>
                      <td className="py-2 px-3 border-l border-slate-200 font-semibold text-slate-900">
                        {item.accountTitle}
                      </td>
                      <td className="py-2 px-3 border-l border-slate-200 text-slate-700">
                        {item.tafsiliTitle || '-'}
                      </td>
                      <td className="py-2 px-3 border-l border-slate-200 text-slate-700">
                        {item.description}
                      </td>
                      <td className="py-2 px-3 border-l border-slate-200 font-mono font-bold text-left text-slate-900">
                        {item.debit > 0 ? item.debit.toLocaleString() : '۰'}
                      </td>
                      <td className="py-2 px-3 font-mono font-bold text-left text-slate-900">
                        {item.credit > 0 ? item.credit.toLocaleString() : '۰'}
                      </td>
                    </tr>
                  ))}
                </tbody>
                <tfoot className="bg-slate-100 font-black border-t-2 border-slate-400">
                  <tr>
                    <td colSpan={5} className="py-2 px-3 border-l border-slate-300 text-right">
                      جمع کل آرتیکل‌های سند:
                    </td>
                    <td className="py-2 px-3 border-l border-slate-300 text-left font-mono text-sm text-indigo-900">
                      {totalDebit.toLocaleString()}
                    </td>
                    <td className="py-2 px-3 text-left font-mono text-sm text-indigo-900">
                      {totalCredit.toLocaleString()}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>

            {/* In Persian words */}
            <div className="p-2.5 bg-slate-50 rounded border border-slate-300 text-xs flex items-center justify-between">
              <div>
                <span className="font-bold text-slate-800">مبلغ سند به حروف: </span>
                <span className="font-semibold text-slate-900">
                  {numberToWordsPersian(totalDebit)} {settings.currency} تمام
                </span>
              </div>
              <div className="flex items-center gap-1 text-emerald-700 font-bold text-[11px]">
                <CheckCircle2 className="w-4 h-4" />
                <span>سند موازنه و تراز است</span>
              </div>
            </div>

            {/* Official Signatures */}
            <div className="grid grid-cols-4 gap-4 pt-8 text-center text-xs font-semibold text-slate-800">
              <div className="space-y-12">
                <div>تنظیم‌کننده سند</div>
                <div className="text-[10px] text-slate-400">امضا و تاریخ</div>
              </div>
              <div className="space-y-12">
                <div>حسابدار مسئول</div>
                <div className="text-[10px] text-slate-400">امضا</div>
              </div>
              <div className="space-y-12">
                <div>مدیر مالی</div>
                <div className="text-[10px] text-slate-400">امضا و مهر</div>
              </div>
              <div className="space-y-12">
                <div>مدیر عامل / هیئت مدیره</div>
                <div className="text-[10px] text-slate-400">امضا و مهر</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
