export type AccountNature = 'debit' | 'credit' | 'both';

export type AccountLevel = 'group' | 'kol' | 'moein' | 'tafsili';

export interface AccountCategory {
  id: string;
  code: string; // e.g. "1" (دارایی‌های جاری), "2" (دارایی‌های غیرجاری), "3" (بدهی‌های جاری), ...
  title: string;
  level: AccountLevel;
  parentCode?: string;
  nature: AccountNature;
  description?: string;
  isSystem?: boolean; // System default accounts that shouldn't be deleted accidentally
}

export interface VoucherItem {
  id: string;
  accountCode: string;
  accountTitle: string;
  tafsiliId?: string;
  tafsiliTitle?: string;
  contactId?: string;
  description: string;
  debit: number;
  credit: number;
}

export type VoucherStatus = 'draft' | 'permanent';

export interface JournalVoucher {
  id: string;
  voucherNumber: number;
  date: string; // YYYY/MM/DD (Shamsi)
  gregorianDate?: string; // ISO date
  description: string;
  referenceNumber?: string;
  type?: 'manual' | 'invoice' | 'settlement' | 'expense' | 'closing' | 'opening';
  items: VoucherItem[];
  status?: VoucherStatus;
  isAutoGenerated?: boolean;
  sourceType?: 'invoice' | 'settlement' | 'expense' | 'manual' | 'closing' | 'opening';
  sourceId?: string;
  createdAt: string;
}

export type ContactType = 'customer' | 'supplier' | 'both' | 'partner' | 'employee' | 'other';

export interface Contact {
  id: string;
  code: string;
  name: string;
  companyName?: string;
  type: ContactType;
  phone: string;
  mobile: string;
  nationalCode?: string;
  economicCode?: string;
  address?: string;
  creditLimit: number;
  initialBalance: number;
  initialBalanceType: 'debit' | 'credit'; // بدهکار (طلبکار از ما) یا بستانکار (بدهکار به ما)
  notes?: string;
  createdAt: string;
}

export type BankAccountType = 'bank' | 'cash' | 'pos';

export interface BankAccount {
  id: string;
  code: string;
  title: string;
  type: BankAccountType;
  bankName: string;
  accountNumber: string;
  cardNumber?: string;
  shebaNumber?: string;
  branchName?: string;
  initialBalance: number;
  notes?: string;
  isActive: boolean;
}

export interface ProductCategory {
  id: string;
  code: string;
  title: string;
  description?: string;
}

export interface Product {
  id: string;
  code: string;
  barcode?: string;
  title: string;
  categoryId: string;
  unit: string; // عدد, کیلوگرم, بسته, متر, ...
  buyPrice: number;
  salePrice: number;
  stockQuantity: number;
  initialStock: number;
  reorderPoint: number;
  description?: string;
}

export interface InvoiceItem {
  id: string;
  productId: string;
  productTitle: string;
  unit: string;
  quantity: number;
  unitPrice: number;
  discountPercent: number;
  discountAmount: number;
  taxPercent: number;
  taxAmount: number;
  totalPrice: number;
}

export interface ChequePayment {
  id: string;
  chequeNumber: string;
  bankName: string;
  amount: number;
  dueDate: string; // YYYY/MM/DD
  sayadNumber?: string;
  drawerName?: string;
  status: 'pending' | 'passed' | 'bounced' | 'returned';
}

export interface MultiSettlement {
  cashPayments: {
    cashId: string;
    cashTitle: string;
    amount: number;
  }[];
  bankPayments: {
    bankId: string;
    bankTitle: string;
    amount: number;
    trackingCode?: string;
  }[];
  chequePayments: ChequePayment[];
  creditAmount: number; // نسیه / مانده در حساب
  discountAmount: number; // تخفیف نقدی پای فاکتور
}

export type InvoiceType = 'sales' | 'purchase' | 'sales_return' | 'purchase_return';

export interface Invoice {
  id: string;
  invoiceNumber: number;
  type: InvoiceType;
  date: string; // YYYY/MM/DD (Shamsi)
  dueDate?: string;
  contactId: string;
  contactName: string;
  contactPhone?: string;
  contactAddress?: string;
  contactEconomicCode?: string;
  items: InvoiceItem[];
  totalItemsDiscount: number;
  totalInvoiceDiscount: number;
  totalTax: number;
  subTotal: number; // مجموع قبل از مالیات و تخفیف
  grandTotal: number; // جمع کل نهایی
  settlement: MultiSettlement;
  notes?: string;
  voucherId?: string; // شماره سند حسابداری صادر شده
  createdAt: string;
}

export interface Expense {
  id: string;
  expenseNumber: number;
  date: string; // YYYY/MM/DD (Shamsi)
  accountCode: string;
  accountTitle: string;
  amount: number;
  paymentType: 'cash' | 'bank' | 'credit';
  sourceAccountId?: string; // cashId or bankId
  sourceAccountTitle?: string;
  trackingNumber?: string;
  beneficiary?: string; // دریافت کننده / شخص
  description: string;
  voucherId?: string;
  createdAt: string;
}

export interface CompanySettings {
  companyName: string;
  financialYear: string;
  tagline: string;
  economicCode: string;
  nationalCode: string;
  registrationNumber: string;
  phone: string;
  mobile: string;
  address: string;
  postalCode: string;
  currency: 'تومان' | 'ریال';
  enableTax: boolean; // فعال بودن یا غیرفعال بودن پیش‌فرض مالیات بر ارزش افزوده
  taxRate: number; // e.g. 10 (%)
  defaultTaxRate: number; // e.g. 10 (%)
  invoiceHeaderNote: string;
  invoiceFooterNote: string;
  autoGenerateVouchers: boolean;
  autoBackupOnClose?: boolean;
}

export interface FinancialYearInfo {
  year: string;
  title: string;
  startDate: string;
  endDate: string;
  isClosed: boolean;
  closedAt?: string;
  closingVoucherId?: string;
  closingVoucherNumber?: number;
  openingVoucherId?: string;
  openingVoucherNumber?: number;
  nextYear?: string;
  notes?: string;
}

export interface BackupSnapshot {
  id: string;
  timestamp: number;
  shamsiDate: string;
  shamsiTime: string;
  reason: string;
  sizeBytes: number;
  counts: {
    invoices: number;
    vouchers: number;
    accounts: number;
    contacts: number;
    products: number;
    expenses: number;
    banks: number;
  };
  payload: string; // Serialized database JSON
}
