import {
  AccountCategory,
  Contact,
  BankAccount,
  ProductCategory,
  Product,
  JournalVoucher,
  Invoice,
  Expense,
  CompanySettings,
  FinancialYearInfo
} from '../types/accounting';
import { getCurrentShamsiDate } from './dateUtils';

export const defaultCompanySettings: CompanySettings = {
  companyName: 'حسابداری مه',
  financialYear: '1403',
  tagline: 'سامانه یکپارچه و استاندارد مالی و بازرگانی',
  economicCode: '411547896325',
  nationalCode: '10103256984',
  registrationNumber: '485921',
  phone: '021-88776655',
  mobile: '09121234567',
  address: 'تهران، خیابان ولیعصر، بالاتر از میدان ونک، برج نگین، طبقه ۵، واحد ۱۲',
  postalCode: '1967834521',
  currency: 'تومان',
  enableTax: true,
  taxRate: 10,
  defaultTaxRate: 10,
  invoiceHeaderNote: 'فروش کالای اصل همراه با گارانتی ۱۸ ماهه معتبر شرکتی',
  invoiceFooterNote: 'کالای فروخته شده تا ۷ روز در صورت عدم مغایرت قابل تعویض می‌باشد. از اعتماد و خرید شما سپاسگزاریم.',
  autoGenerateVouchers: true,
  autoBackupOnClose: true,
};

export const defaultFinancialYears: FinancialYearInfo[] = [
  {
    year: '1403',
    title: 'سال مالی ۱۴۰۳ (جاری)',
    startDate: '1403/01/01',
    endDate: '1403/12/29',
    isClosed: false,
    notes: 'سال مالی فعال و جاری کسب‌وکار'
  },
  {
    year: '1402',
    title: 'سال مالی ۱۴۰۲ (بسته شده)',
    startDate: '1402/01/01',
    endDate: '1402/12/29',
    isClosed: true,
    closedAt: '1402/12/29',
    closingVoucherNumber: 999,
    openingVoucherNumber: 1,
    nextYear: '1403',
    notes: 'حساب‌های موقت و دائم با استانداردهای حسابداری بسته شده و به سال ۱۴۰۳ منتقل شده‌اند'
  }
];

export const defaultChartOfAccounts: AccountCategory[] = [
  // 1. دارایی‌های جاری
  { id: 'acc-1', code: '1', title: 'دارایی‌های جاری', level: 'group', nature: 'debit', isSystem: true },
  { id: 'acc-101', code: '101', parentCode: '1', title: 'موجودی نقد و بانک', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-10101', code: '10101', parentCode: '101', title: 'صندوق‌ها', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-10102', code: '10102', parentCode: '101', title: 'حساب‌های بانکی ریالی', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-10103', code: '10103', parentCode: '101', title: 'تنخواه‌گردان‌ها', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-10104', code: '10104', parentCode: '101', title: 'دستگاه‌های کارتخوان (POS)', level: 'moein', nature: 'debit', isSystem: true },
  
  { id: 'acc-102', code: '102', parentCode: '1', title: 'اسناد دریافتنی تجاری', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-10201', code: '10201', parentCode: '102', title: 'چک‌های دریافتی نزد صندوق', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-10202', code: '10202', parentCode: '102', title: 'اسناد در جریان وصول', level: 'moein', nature: 'debit', isSystem: true },

  { id: 'acc-103', code: '103', parentCode: '1', title: 'حساب‌های دریافتنی تجاری (بدهکاران)', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-10301', code: '10301', parentCode: '103', title: 'مشتریان تجاری داخلی', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-10302', code: '10302', parentCode: '103', title: 'سایر حساب‌های دریافتنی', level: 'moein', nature: 'debit', isSystem: true },

  { id: 'acc-104', code: '104', parentCode: '1', title: 'موجودی مواد و کالا', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-10401', code: '10401', parentCode: '104', title: 'موجودی کالای انبار مرکزی', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-10402', code: '10402', parentCode: '104', title: 'کالای در راه', level: 'moein', nature: 'debit', isSystem: true },

  { id: 'acc-105', code: '105', parentCode: '1', title: 'پیش‌پرداخت‌ها و علی‌الحساب‌ها', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-10501', code: '10501', parentCode: '105', title: 'پیش‌پرداخت خرید کالا و خدمات', level: 'moein', nature: 'debit', isSystem: true },

  // 2. دارایی‌های غیرجاری
  { id: 'acc-2', code: '2', title: 'دارایی‌های غیرجاری', level: 'group', nature: 'debit', isSystem: true },
  { id: 'acc-201', code: '201', parentCode: '2', title: 'دارایی‌های ثابت مشهود', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-20101', code: '20101', parentCode: '201', title: 'اثاثه و منصوبات اداری', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-20102', code: '20102', parentCode: '201', title: 'وسایط نقلیه', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-20103', code: '20103', parentCode: '201', title: 'رایانه و تجهیزات الکترونیکی', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-202', code: '202', parentCode: '2', title: 'استهلاک انباشته دارایی‌های ثابت', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-20201', code: '20201', parentCode: '202', title: 'استهلاک انباشته اموال و تجهیزات', level: 'moein', nature: 'credit', isSystem: true },

  // 3. بدهی‌های جاری
  { id: 'acc-3', code: '3', title: 'بدهی‌های جاری', level: 'group', nature: 'credit', isSystem: true },
  { id: 'acc-301', code: '301', parentCode: '3', title: 'حساب‌های پرداختنی تجاری (بستانکاران)', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-30101', code: '30101', parentCode: '301', title: 'تامین‌کنندگان کالا و خدمات', level: 'moein', nature: 'credit', isSystem: true },
  
  { id: 'acc-302', code: '302', parentCode: '3', title: 'اسناد پرداختنی تجاری', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-30201', code: '30201', parentCode: '302', title: 'چک‌های پرداختنی عهده بانک‌ها', level: 'moein', nature: 'credit', isSystem: true },

  { id: 'acc-303', code: '303', parentCode: '3', title: 'سایر بدهی‌ها و ذخایر', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-30301', code: '30301', parentCode: '303', title: 'مالیات و عوارض بر ارزش افزوده پرداختنی', level: 'moein', nature: 'credit', isSystem: true },
  { id: 'acc-30302', code: '30302', parentCode: '303', title: 'حقوق و دستمزد پرداختنی', level: 'moein', nature: 'credit', isSystem: true },
  { id: 'acc-30303', code: '30303', parentCode: '303', title: 'بیمه پرداختنی', level: 'moein', nature: 'credit', isSystem: true },

  // 4. حقوق صاحبان سهام و سرمایه
  { id: 'acc-4', code: '4', title: 'حقوق مالکانه و سرمایه', level: 'group', nature: 'credit', isSystem: true },
  { id: 'acc-401', code: '401', parentCode: '4', title: 'سرمایه اولیه و ثبت شده', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-40101', code: '40101', parentCode: '401', title: 'سرمایه شرکا و موسسین', level: 'moein', nature: 'credit', isSystem: true },
  { id: 'acc-402', code: '402', parentCode: '4', title: 'سود و زیان انباشته', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-40201', code: '40201', parentCode: '402', title: 'سود/زیان انباشته سنواتی', level: 'moein', nature: 'credit', isSystem: true },
  { id: 'acc-403', code: '403', parentCode: '4', title: 'جاری شرکا و سهامداران', level: 'kol', nature: 'both', isSystem: true },
  { id: 'acc-40301', code: '40301', parentCode: '403', title: 'حساب جاری شرکا', level: 'moein', nature: 'both', isSystem: true },
  { id: 'acc-40302', code: '40302', parentCode: '403', title: 'برداشت‌های جاری شرکا', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-40303', code: '40303', parentCode: '403', title: 'واریز و آورده شرکا', level: 'moein', nature: 'credit', isSystem: true },

  // 5. درآمدها و فروش
  { id: 'acc-5', code: '5', title: 'درآمدها', level: 'group', nature: 'credit', isSystem: true },
  { id: 'acc-501', code: '501', parentCode: '5', title: 'فروش ناخالص کالا و خدمات', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-50101', code: '50101', parentCode: '501', title: 'فروش کالای بازرگانی', level: 'moein', nature: 'credit', isSystem: true },
  { id: 'acc-50102', code: '50102', parentCode: '501', title: 'ارائه خدمات فنی و اجرایی', level: 'moein', nature: 'credit', isSystem: true },
  { id: 'acc-502', code: '502', parentCode: '5', title: 'برگشت از فروش و تخفیفات', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-50201', code: '50201', parentCode: '502', title: 'برگشت از فروش کالا', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-50202', code: '50202', parentCode: '502', title: 'تخفیفات نقدی اعطایی فروش', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-503', code: '503', parentCode: '5', title: 'سایر درآمدهای غیرعملیاتی', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-50301', code: '50301', parentCode: '503', title: 'سود سپرده‌های بانکی', level: 'moein', nature: 'credit', isSystem: true },

  // 6. بهای تمام شده کالای فروش رفته و خرید
  { id: 'acc-6', code: '6', title: 'بهای تمام شده', level: 'group', nature: 'debit', isSystem: true },
  { id: 'acc-601', code: '601', parentCode: '6', title: 'بهای تمام شده کالای فروش رفته', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-60101', code: '60101', parentCode: '601', title: 'بهای تمام شده کالای فروش رفته', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-602', code: '602', parentCode: '6', title: 'خرید کالا و ملزومات', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-60201', code: '60201', parentCode: '602', title: 'خرید کالای بازرگانی', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-603', code: '603', parentCode: '6', title: 'برگشت از خرید و تخفیفات', level: 'kol', nature: 'credit', isSystem: true },
  { id: 'acc-60301', code: '60301', parentCode: '603', title: 'برگشت از خرید کالا', level: 'moein', nature: 'credit', isSystem: true },
  { id: 'acc-60302', code: '60302', parentCode: '603', title: 'تخفیفات نقدی کسب شده خرید', level: 'moein', nature: 'credit', isSystem: true },

  // 7. هزینه‌های اداری، عمومی و توزیع و فروش
  { id: 'acc-7', code: '7', title: 'هزینه‌ها', level: 'group', nature: 'debit', isSystem: true },
  { id: 'acc-701', code: '701', parentCode: '7', title: 'هزینه‌های حقوق و دستمزد پرسنل', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-70101', code: '70101', parentCode: '701', title: 'حقوق و مزایای کارکنان', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70102', code: '70102', parentCode: '701', title: 'حق بیمه سهم کارفرما', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70103', code: '70103', parentCode: '701', title: 'پاداش، عیدی و سنوات', level: 'moein', nature: 'debit', isSystem: true },

  { id: 'acc-702', code: '702', parentCode: '7', title: 'هزینه‌های عمومی و اداری', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-70201', code: '70201', parentCode: '702', title: 'هزینه اجاره دفتر و انبار', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70202', code: '70202', parentCode: '702', title: 'هزینه آب، برق، گاز و تلفن و اینترنت', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70203', code: '70203', parentCode: '702', title: 'هزینه ملزومات اداری و مصرفی', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70204', code: '70204', parentCode: '702', title: 'هزینه پذیرایی، آبدارخانه و جلسات', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70205', code: '70205', parentCode: '702', title: 'هزینه تعمیرات و نگهداری تجهیزات', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70206', code: '70206', parentCode: '702', title: 'هزینه ایاب و ذهاب و سفر', level: 'moein', nature: 'debit', isSystem: true },

  { id: 'acc-703', code: '703', parentCode: '7', title: 'هزینه‌های بازاریابی و فروش', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-70301', code: '70301', parentCode: '703', title: 'هزینه تبلیغات و بازاریابی دیجیتال', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70302', code: '70302', parentCode: '703', title: 'هزینه حمل و نقل، ارسال و پیک', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70303', code: '70303', parentCode: '703', title: 'پورسانت و کارمزد فروش', level: 'moein', nature: 'debit', isSystem: true },

  { id: 'acc-704', code: '704', parentCode: '7', title: 'هزینه‌های مالی و کارمزد بانکی', level: 'kol', nature: 'debit', isSystem: true },
  { id: 'acc-70401', code: '70401', parentCode: '704', title: 'کارمزد خدمات بانکی و دستگاه پوز', level: 'moein', nature: 'debit', isSystem: true },
  { id: 'acc-70402', code: '70402', parentCode: '704', title: 'هزینه بهره و تسهیلات مالی', level: 'moein', nature: 'debit', isSystem: true },

  // 8. حساب‌های بستن و انتظامی (استاندارد بستن سال مالی)
  { id: 'acc-8', code: '8', title: 'حساب‌های بستن و انتظامی', level: 'group', nature: 'both', isSystem: true },
  { id: 'acc-801', code: '801', parentCode: '8', title: 'خلاصه سود و زیان عملکرد سال', level: 'kol', nature: 'both', isSystem: true },
  { id: 'acc-80101', code: '80101', parentCode: '801', title: 'خلاصه سود و زیان (بستن حساب‌های موقت)', level: 'moein', nature: 'both', isSystem: true },
  { id: 'acc-802', code: '802', parentCode: '8', title: 'تراز اختتامیه و افتتاحیه', level: 'kol', nature: 'both', isSystem: true },
  { id: 'acc-80201', code: '80201', parentCode: '802', title: 'تراز اختتامیه / افتتاحیه انتقالی', level: 'moein', nature: 'both', isSystem: true },
];

export const defaultContacts: Contact[] = [
  {
    id: 'cnt-1',
    code: '1001',
    name: 'شرکت مهندسی داده‌پردازان سپهر',
    companyName: 'داده‌پردازان سپهر',
    type: 'customer',
    phone: '021-88997711',
    mobile: '09123456789',
    nationalCode: '10108844332',
    economicCode: '411223344556',
    address: 'تهران، خیابان مطهری، پلاک ۲۳۴، طبقه ۳',
    creditLimit: 500000000,
    initialBalance: 0,
    initialBalanceType: 'debit',
    notes: 'مشتری حقوقی معتبر و پروژه‌ای با پرداخت‌های منظم',
    createdAt: '1403/01/10',
  },
  {
    id: 'cnt-2',
    code: '1002',
    name: 'آقای دکتر علی محمدی',
    companyName: 'مطب دکتر محمدی',
    type: 'customer',
    phone: '021-22446688',
    mobile: '09121112233',
    nationalCode: '0078945612',
    economicCode: '',
    address: 'تهران، زعفرانیه، خیابان آصف، کوچه پنجم، پلاک ۸',
    creditLimit: 150000000,
    initialBalance: 12000000,
    initialBalanceType: 'debit',
    notes: 'مشتری دائمی و VIP تجهیزات دیجیتال',
    createdAt: '1403/02/01',
  },
  {
    id: 'cnt-3',
    code: '1003',
    name: 'بازرگانی آریا سیستم (واردات و پخش)',
    companyName: 'آریا سیستم خاورمیانه',
    type: 'supplier',
    phone: '021-66778899',
    mobile: '09125556677',
    nationalCode: '10320098741',
    economicCode: '411889966554',
    address: 'تهران، خیابان جمهوری، تقاطع فردوسی، پاساژ یگانه، طبقه همکف، پلاک ۱۰',
    creditLimit: 1200000000,
    initialBalance: 45000000,
    initialBalanceType: 'credit',
    notes: 'تامین‌کننده اصلی مانیتور و لپ‌تاپ‌های ایسوس و لنوو',
    createdAt: '1403/01/15',
  },
  {
    id: 'cnt-4',
    code: '1004',
    name: 'فروشگاه الکترونیک سامان (آقای رضایی)',
    companyName: 'سامان الکترونیک',
    type: 'both',
    phone: '021-33112233',
    mobile: '09129998877',
    nationalCode: '0065432198',
    economicCode: '',
    address: 'تهران، میدان امام خمینی، پاساژ فتوت، واحد ۴۵',
    creditLimit: 300000000,
    initialBalance: 0,
    initialBalanceType: 'debit',
    notes: 'همکار تجاری (خرید قطعات و فروش سیستم‌های کامل)',
    createdAt: '1403/02/20',
  },
  {
    id: 'cnt-5',
    code: '1005',
    name: 'خانم مهندس مریم کیانی',
    companyName: 'استودیو طراحی کیان',
    type: 'customer',
    phone: '021-44556677',
    mobile: '09127774411',
    nationalCode: '0081234567',
    economicCode: '',
    address: 'تهران، سعادت‌آباد، خیابان علامه شمالی، پلاک ۱۸',
    creditLimit: 200000000,
    initialBalance: 0,
    initialBalanceType: 'debit',
    notes: 'خریدار مانیتورهای طراحی و سیستم‌های تدوین',
    createdAt: '1403/03/05',
  },
  {
    id: 'cnt-6',
    code: '1006',
    name: 'مهندس مهدی حسینی (شریک موسس)',
    companyName: 'حسابداری مه',
    type: 'partner',
    phone: '021-88776655',
    mobile: '09121110022',
    nationalCode: '0075544332',
    economicCode: '',
    address: 'تهران، ونک، برج نگین',
    creditLimit: 0,
    initialBalance: 250000000,
    initialBalanceType: 'credit',
    notes: 'شریک اصلی و مدیر عامل با سهم‌الشرکه ۵۰٪ (کد معین ۴۰۳۰۱)',
    createdAt: '1403/01/01',
  },
  {
    id: 'cnt-7',
    code: '1007',
    name: 'دکتر سارا راد (شریک سرمایه‌گذار)',
    companyName: 'حسابداری مه',
    type: 'partner',
    phone: '021-88776656',
    mobile: '09123334455',
    nationalCode: '0089988776',
    economicCode: '',
    address: 'تهران، ونک، برج نگین',
    creditLimit: 0,
    initialBalance: 250000000,
    initialBalanceType: 'credit',
    notes: 'شریک سرمایه‌گذار با سهم‌الشرکه ۵۰٪ (کد معین ۴۰۳۰۱)',
    createdAt: '1403/01/01',
  }
];

export const defaultBankAccounts: BankAccount[] = [
  {
    id: 'bank-1',
    code: 'B-01',
    title: 'حساب جاری بانک ملت (شعبه ونک)',
    type: 'bank',
    bankName: 'بانک ملت',
    accountNumber: '4820198425',
    cardNumber: '6104-3378-9123-4567',
    shebaNumber: 'IR820120000000004820198425',
    branchName: 'شعبه ونک تهران (کد ۱۲۴۰)',
    initialBalance: 385000000,
    notes: 'حساب اصلی درآمدها و تراکنش‌های اینترنتی شرکت',
    isActive: true,
  },
  {
    id: 'bank-2',
    code: 'B-02',
    title: 'حساب جاری بانک سامان (شعبه مرکزی)',
    type: 'bank',
    bankName: 'بانک سامان',
    accountNumber: '824-810-9421-1',
    cardNumber: '6219-8610-3344-5566',
    shebaNumber: 'IR560560082481009421001001',
    branchName: 'شعبه مرکزی تهران',
    initialBalance: 190000000,
    notes: 'حساب تسویه چک‌های صیادی و پرداخت به تامین‌کنندگان',
    isActive: true,
  },
  {
    id: 'bank-3',
    code: 'B-03',
    title: 'حساب بانک ملی ایران (شعبه میرداماد)',
    type: 'bank',
    bankName: 'بانک ملی',
    accountNumber: '0105849201004',
    cardNumber: '6037-9918-7744-1122',
    shebaNumber: 'IR940170000000105849201004',
    branchName: 'شعبه میرداماد',
    initialBalance: 75000000,
    notes: 'حساب واریز حقوق و دستمزد پرسنل',
    isActive: true,
  },
  {
    id: 'cash-1',
    code: 'C-01',
    title: 'صندوق مرکزی شرکت',
    type: 'cash',
    bankName: 'صندوق نقدی',
    accountNumber: 'صندوق شماره ۱',
    initialBalance: 24500000,
    notes: 'موجودی اسکناس و نقدینگی در محل شرکت',
    isActive: true,
  },
  {
    id: 'pos-1',
    code: 'P-01',
    title: 'دستگاه کارتخوان فروشگاه (به‌پرداخت ملت)',
    type: 'pos',
    bankName: 'به‌پرداخت ملت (متصل به حساب ملت)',
    accountNumber: 'ترمینال: 9482104',
    initialBalance: 0,
    notes: 'پوز مستقر در بخش فروش و تحویل حضوری',
    isActive: true,
  }
];

export const defaultProductCategories: ProductCategory[] = [
  { id: 'cat-1', code: 'CAT-01', title: 'لپ‌تاپ و آل‌این‌وان', description: 'انواع لپ‌تاپ‌های اداری، مهندسی و گیمینگ' },
  { id: 'cat-2', code: 'CAT-02', title: 'مانیتور و نمایشگر', description: 'نمایشگرهای تخصصی، گیمینگ و اداری' },
  { id: 'cat-3', code: 'CAT-03', title: 'قطعات و لوازم جانبی رایانه', description: 'ماوس، کیبورد، هدست، هارد اکسترنال و فلش' },
  { id: 'cat-4', code: 'CAT-04', title: 'تجهیزات شبکه و سرور', description: 'مودم، روتر، سوئیچ و کابل‌های ارتباطی' },
  { id: 'cat-5', code: 'CAT-05', title: 'خدمات فنی و پشتیبانی', description: 'نصب، راه‌اندازی و خدمات پس از فروش' },
];

export const defaultProducts: Product[] = [
  {
    id: 'prd-1',
    code: 'PRD-101',
    barcode: '6260198421015',
    title: 'لپ‌تاپ ایسوس Asus ZenBook 14 OLED (Core i7 / 16GB / 1TB SSD)',
    categoryId: 'cat-1',
    unit: 'دستگاه',
    buyPrice: 62000000,
    salePrice: 74500000,
    stockQuantity: 12,
    initialStock: 15,
    reorderPoint: 4,
    description: 'اولترابوک سبک با صفحه‌نمایش 2.8K OLED، گارانتی ۲ ساله یکپارچه سازگار',
  },
  {
    id: 'prd-2',
    code: 'PRD-102',
    barcode: '6260198421022',
    title: 'لپ‌تاپ لنوو Lenovo Legion 5 Pro (Ryzen 7 / 32GB / RTX 4060)',
    categoryId: 'cat-1',
    unit: 'دستگاه',
    buyPrice: 81000000,
    salePrice: 96000000,
    stockQuantity: 7,
    initialStock: 10,
    reorderPoint: 3,
    description: 'لپ‌تاپ گیمینگ و مهندسی قدرتمند مناسب رندرینگ و طراحی ۳D',
  },
  {
    id: 'prd-3',
    code: 'PRD-103',
    barcode: '6260198421039',
    title: 'مانیتور ۲۷ اینچ دل Dell UltraSharp 4K UHD IPS (U2723QE)',
    categoryId: 'cat-2',
    unit: 'عدد',
    buyPrice: 31000000,
    salePrice: 38500000,
    stockQuantity: 18,
    initialStock: 20,
    reorderPoint: 5,
    description: 'نمایشگر فوق‌العاده با دقت رنگ بالا برای طراحان گرافیک و تدوین‌گران',
  },
  {
    id: 'prd-4',
    code: 'PRD-104',
    barcode: '6260198421046',
    title: 'مانیتور گیمینگ سامسونگ ۲۴ اینچ Odyssey G3 165Hz',
    categoryId: 'cat-2',
    unit: 'عدد',
    buyPrice: 8500000,
    salePrice: 11200000,
    stockQuantity: 24,
    initialStock: 30,
    reorderPoint: 6,
    description: 'مانیتور با پاسخ‌دهی ۱ میلی‌ثانیه و فریم‌ریت بالا',
  },
  {
    id: 'prd-5',
    code: 'PRD-105',
    barcode: '6260198421053',
    title: 'کیبورد و ماوس بی‌سیم لاجیتک Logitech MK295 Silent',
    categoryId: 'cat-3',
    unit: 'بسته',
    buyPrice: 1650000,
    salePrice: 2250000,
    stockQuantity: 45,
    initialStock: 50,
    reorderPoint: 15,
    description: 'ست ماوس و کیبورد بی‌صدا با فناوری SilentTouch لاجیتک',
  },
  {
    id: 'prd-6',
    code: 'PRD-106',
    barcode: '6260198421060',
    title: 'هارد اکسترنال ضدضربه ای‌دیتا ADATA HD710 Pro 2TB',
    categoryId: 'cat-3',
    unit: 'عدد',
    buyPrice: 4200000,
    salePrice: 5300000,
    stockQuantity: 32,
    initialStock: 40,
    reorderPoint: 10,
    description: 'ضد آب، ضد گرد و غبار با روکش سیلیکونی مقاوم و حسگر G-Shock',
  },
  {
    id: 'prd-7',
    code: 'PRD-107',
    barcode: '6260198421077',
    title: 'روتر دو بانده گیگابیت تی‌پی لینک TP-Link Archer AX55 Wi-Fi 6',
    categoryId: 'cat-4',
    unit: 'عدد',
    buyPrice: 3800000,
    salePrice: 4950000,
    stockQuantity: 14,
    initialStock: 20,
    reorderPoint: 5,
    description: 'پشتیبانی از فناوری جدید Wi-Fi 6 سرعت ۳۰۰۰ مگابیت با پوشش وسیع',
  },
  {
    id: 'prd-8',
    code: 'PRD-108',
    barcode: '6260198421084',
    title: 'خدمات نصب، راه‌اندازی شبکه و پیکربندی امنیتی سیستم‌ها',
    categoryId: 'cat-5',
    unit: 'نفر ساعت',
    buyPrice: 0,
    salePrice: 1500000,
    stockQuantity: 999,
    initialStock: 999,
    reorderPoint: 0,
    description: 'خدمات تخصصی پشتیبانی فنی در محل مشتری',
  },
];

export const defaultExpenses: Expense[] = [
  {
    id: 'exp-1',
    expenseNumber: 101,
    date: '1403/05/01',
    accountCode: '70201',
    accountTitle: 'هزینه اجاره دفتر و انبار',
    amount: 45000000,
    paymentType: 'bank',
    sourceAccountId: 'bank-1',
    sourceAccountTitle: 'حساب جاری بانک ملت (شعبه ونک)',
    trackingNumber: 'TRX-94821',
    beneficiary: 'آقای خسروی (مالک ساختمان)',
    description: 'پرداخت اجاره بهای دفتر مرکزی مربوط به مرداد ماه ۱۴۰۳',
    voucherId: 'vch-102',
    createdAt: '1403/05/01',
  },
  {
    id: 'exp-2',
    expenseNumber: 102,
    date: '1403/05/05',
    accountCode: '70202',
    accountTitle: 'هزینه آب، برق، گاز و تلفن و اینترنت',
    amount: 6800000,
    paymentType: 'bank',
    sourceAccountId: 'bank-1',
    sourceAccountTitle: 'حساب جاری بانک ملت (شعبه ونک)',
    trackingNumber: 'TRX-98203',
    beneficiary: 'شرکت مخابرات و توزیع برق',
    description: 'پرداخت قبوض اشتراک اینترنت پرسرعت فیبر نوری و برق دفتر',
    voucherId: 'vch-103',
    createdAt: '1403/05/05',
  },
  {
    id: 'exp-3',
    expenseNumber: 103,
    date: '1403/05/10',
    accountCode: '70302',
    accountTitle: 'هزینه حمل و نقل، ارسال و پیک',
    amount: 3400000,
    paymentType: 'cash',
    sourceAccountId: 'cash-1',
    sourceAccountTitle: 'صندوق مرکزی شرکت',
    trackingNumber: '',
    beneficiary: 'پیک بادپا و تیپاکس',
    description: 'هزینه ارسال محموله‌های فاکتورهای مشتریان تهران و شهرستان',
    voucherId: 'vch-104',
    createdAt: '1403/05/10',
  },
  {
    id: 'exp-4',
    expenseNumber: 104,
    date: '1403/05/15',
    accountCode: '70204',
    accountTitle: 'هزینه پذیرایی، آبدارخانه و جلسات',
    amount: 2900000,
    paymentType: 'cash',
    sourceAccountId: 'cash-1',
    sourceAccountTitle: 'صندوق مرکزی شرکت',
    trackingNumber: '',
    beneficiary: 'فروشگاه کوروش و هایپراستار',
    description: 'خرید چای، قند، قهوه و ملزومات پذیرایی پرسنل و مهمانان جلسات',
    voucherId: 'vch-105',
    createdAt: '1403/05/15',
  },
];

export const defaultInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 1001,
    type: 'sales',
    date: '1403/05/12',
    dueDate: '1403/06/12',
    contactId: 'cnt-1',
    contactName: 'شرکت مهندسی داده‌پردازان سپهر',
    contactPhone: '021-88997711',
    contactAddress: 'تهران، خیابان مطهری، پلاک ۲۳۴، طبقه ۳',
    contactEconomicCode: '411223344556',
    items: [
      {
        id: 'item-1',
        productId: 'prd-1',
        productTitle: 'لپ‌تاپ ایسوس Asus ZenBook 14 OLED (Core i7 / 16GB / 1TB SSD)',
        unit: 'دستگاه',
        quantity: 2,
        unitPrice: 74500000,
        discountPercent: 2,
        discountAmount: 2980000,
        taxPercent: 10,
        taxAmount: 14602000,
        totalPrice: 160622000,
      },
      {
        id: 'item-2',
        productId: 'prd-3',
        productTitle: 'مانیتور ۲۷ اینچ دل Dell UltraSharp 4K UHD IPS (U2723QE)',
        unit: 'عدد',
        quantity: 2,
        unitPrice: 38500000,
        discountPercent: 0,
        discountAmount: 0,
        taxPercent: 10,
        taxAmount: 7700000,
        totalPrice: 84700000,
      }
    ],
    totalItemsDiscount: 2980000,
    totalInvoiceDiscount: 1000000, // تخفیف اضافه پای فاکتور
    totalTax: 22302000,
    subTotal: 226000000,
    grandTotal: 244322000,
    settlement: {
      cashPayments: [
        { cashId: 'cash-1', cashTitle: 'صندوق مرکزی شرکت', amount: 14322000 }
      ],
      bankPayments: [
        { bankId: 'bank-1', bankTitle: 'حساب جاری بانک ملت (شعبه ونک)', amount: 130000000, trackingCode: 'SAT-9812401' }
      ],
      chequePayments: [
        {
          id: 'chq-1',
          chequeNumber: '84920194',
          bankName: 'بانک پاسارگاد',
          amount: 100000000,
          dueDate: '1403/06/20',
          sayadNumber: '1982740192841920',
          drawerName: 'شرکت داده‌پردازان سپهر',
          status: 'pending'
        }
      ],
      creditAmount: 0,
      discountAmount: 1000000
    },
    notes: 'فروش به شرکت داده‌پردازان سپهر همراه با نصب و گارانتی شرکتی',
    voucherId: 'vch-106',
    createdAt: '1403/05/12',
  },
  {
    id: 'inv-2',
    invoiceNumber: 1002,
    type: 'sales',
    date: '1403/05/18',
    dueDate: '1403/06/18',
    contactId: 'cnt-2',
    contactName: 'آقای دکتر علی محمدی',
    contactPhone: '021-22446688',
    contactAddress: 'تهران، زعفرانیه، خیابان آصف، کوچه پنجم، پلاک ۸',
    contactEconomicCode: '',
    items: [
      {
        id: 'item-3',
        productId: 'prd-2',
        productTitle: 'لپ‌تاپ لنوو Lenovo Legion 5 Pro (Ryzen 7 / 32GB / RTX 4060)',
        unit: 'دستگاه',
        quantity: 1,
        unitPrice: 96000000,
        discountPercent: 0,
        discountAmount: 0,
        taxPercent: 10,
        taxAmount: 9600000,
        totalPrice: 105600000,
      },
      {
        id: 'item-4',
        productId: 'prd-5',
        productTitle: 'کیبورد و ماوس بی‌سیم لاجیتک Logitech MK295 Silent',
        unit: 'بسته',
        quantity: 1,
        unitPrice: 2250000,
        discountPercent: 0,
        discountAmount: 0,
        taxPercent: 10,
        taxAmount: 225000,
        totalPrice: 2475000,
      }
    ],
    totalItemsDiscount: 0,
    totalInvoiceDiscount: 0,
    totalTax: 9825000,
    subTotal: 98250000,
    grandTotal: 108075000,
    settlement: {
      cashPayments: [],
      bankPayments: [
        { bankId: 'pos-1', bankTitle: 'دستگاه کارتخوان فروشگاه (به‌پرداخت ملت)', amount: 68075000, trackingCode: 'POS-77412' }
      ],
      chequePayments: [],
      creditAmount: 40000000, // نسیه
      discountAmount: 0
    },
    notes: 'تحویل حضوری با پرداخت کارتخوان و مانده در حساب',
    voucherId: 'vch-107',
    createdAt: '1403/05/18',
  },
  {
    id: 'inv-3',
    invoiceNumber: 2001,
    type: 'purchase',
    date: '1403/05/02',
    dueDate: '1403/06/02',
    contactId: 'cnt-3',
    contactName: 'بازرگانی آریا سیستم (واردات و پخش)',
    contactPhone: '021-66778899',
    contactAddress: 'تهران، خیابان جمهوری، تقاطع فردوسی، پاساژ یگانه، پلاک ۱۰',
    contactEconomicCode: '411889966554',
    items: [
      {
        id: 'item-5',
        productId: 'prd-1',
        productTitle: 'لپ‌تاپ ایسوس Asus ZenBook 14 OLED (Core i7 / 16GB / 1TB SSD)',
        unit: 'دستگاه',
        quantity: 5,
        unitPrice: 62000000,
        discountPercent: 0,
        discountAmount: 0,
        taxPercent: 10,
        taxAmount: 31000000,
        totalPrice: 341000000,
      },
      {
        id: 'item-6',
        productId: 'prd-6',
        productTitle: 'هارد اکسترنال ضدضربه ای‌دیتا ADATA HD710 Pro 2TB',
        unit: 'عدد',
        quantity: 10,
        unitPrice: 4200000,
        discountPercent: 0,
        discountAmount: 0,
        taxPercent: 10,
        taxAmount: 4200000,
        totalPrice: 46200000,
      }
    ],
    totalItemsDiscount: 0,
    totalInvoiceDiscount: 2000000,
    totalTax: 35200000,
    subTotal: 352000000,
    grandTotal: 385200000,
    settlement: {
      cashPayments: [],
      bankPayments: [
        { bankId: 'bank-2', bankTitle: 'حساب جاری بانک سامان (شعبه مرکزی)', amount: 200000000, trackingCode: 'PAY-11029' }
      ],
      chequePayments: [
        {
          id: 'chq-2',
          chequeNumber: '77665544',
          bankName: 'بانک سامان',
          amount: 185200000,
          dueDate: '1403/06/30',
          sayadNumber: '2987102948172940',
          drawerName: 'شرکت بازرگانی پارس نوین',
          status: 'pending'
        }
      ],
      creditAmount: 0,
      discountAmount: 2000000
    },
    notes: 'خرید پارت جدید لپ‌تاپ و تجهیزات ذخیره‌سازی از بازرگانی آریا سیستم',
    voucherId: 'vch-108',
    createdAt: '1403/05/02',
  },
  {
    id: 'inv-4',
    invoiceNumber: 1003,
    type: 'sales_return',
    date: '1403/05/22',
    dueDate: '',
    contactId: 'cnt-2',
    contactName: 'آقای دکتر علی محمدی',
    contactPhone: '021-22446688',
    contactAddress: 'تهران، زعفرانیه، خیابان آصف',
    contactEconomicCode: '',
    items: [
      {
        id: 'item-7',
        productId: 'prd-5',
        productTitle: 'کیبورد و ماوس بی‌سیم لاجیتک Logitech MK295 Silent',
        unit: 'بسته',
        quantity: 1,
        unitPrice: 2250000,
        discountPercent: 0,
        discountAmount: 0,
        taxPercent: 10,
        taxAmount: 225000,
        totalPrice: 2475000,
      }
    ],
    totalItemsDiscount: 0,
    totalInvoiceDiscount: 0,
    totalTax: 225000,
    subTotal: 2250000,
    grandTotal: 2475000,
    settlement: {
      cashPayments: [],
      bankPayments: [],
      chequePayments: [],
      creditAmount: 2475000, // کسر از مانده بدهی مشتری
      discountAmount: 0
    },
    notes: 'مرجوعی ست ماوس و کیبورد به علت عدم نیاز مشتری و کسر از بدهی وی',
    voucherId: 'vch-109',
    createdAt: '1403/05/22',
  }
];

export const defaultJournalVouchers: JournalVoucher[] = [
  {
    id: 'vch-101',
    voucherNumber: 101,
    date: '1403/01/05',
    gregorianDate: '2024-03-24',
    description: 'سند افتتاحیه دوره مالی و ثبت موجودی‌های اولیه صندوق، بانک و سرمایه شرکا',
    status: 'permanent',
    isAutoGenerated: false,
    sourceType: 'manual',
    createdAt: '1403/01/05',
    items: [
      {
        id: 'vi-1',
        accountCode: '10101',
        accountTitle: 'صندوق‌ها',
        tafsiliTitle: 'صندوق مرکزی شرکت',
        description: 'موجودی اولیه صندوق نقدینگی',
        debit: 24500000,
        credit: 0,
      },
      {
        id: 'vi-2',
        accountCode: '10102',
        accountTitle: 'حساب‌های بانکی ریالی',
        tafsiliTitle: 'بانک ملت و سامان',
        description: 'موجودی اولیه حساب‌های بانکی',
        debit: 650000000,
        credit: 0,
      },
      {
        id: 'vi-3',
        accountCode: '10401',
        accountTitle: 'موجودی کالای انبار مرکزی',
        tafsiliTitle: 'انبار مرکزی دیجیتال',
        description: 'ارزش موجودی کالای اول دوره انبار',
        debit: 1125000000,
        credit: 0,
      },
      {
        id: 'vi-4',
        accountCode: '40101',
        accountTitle: 'سرمایه شرکا و موسسین',
        tafsiliTitle: 'سهامداران اصلی',
        description: 'سرمایه اولیه ثبت شده شرکت در آغاز دوره مالی',
        debit: 0,
        credit: 1799500000,
      }
    ]
  },
  {
    id: 'vch-102',
    voucherNumber: 102,
    date: '1403/05/01',
    gregorianDate: '2024-07-22',
    description: 'ثبت هزینه اجاره مرداد ماه دفتر مرکزی شرکت',
    status: 'permanent',
    isAutoGenerated: true,
    sourceType: 'expense',
    sourceId: 'exp-1',
    createdAt: '1403/05/01',
    items: [
      {
        id: 'vi-5',
        accountCode: '70201',
        accountTitle: 'هزینه اجاره دفتر و انبار',
        tafsiliTitle: 'دفتر مرکزی ونک',
        description: 'اجاره بهای مرداد ماه پرداخت به آقای خسروی',
        debit: 45000000,
        credit: 0,
      },
      {
        id: 'vi-6',
        accountCode: '10102',
        accountTitle: 'حساب‌های بانکی ریالی',
        tafsiliTitle: 'بانک ملت ونک',
        description: 'واریز اینترنتی اجاره بها',
        debit: 0,
        credit: 45000000,
      }
    ]
  },
  {
    id: 'vch-106',
    voucherNumber: 106,
    date: '1403/05/12',
    gregorianDate: '2024-08-02',
    description: 'ثبت فروش فاکتور شماره ۱۰۰۱ به شرکت مهندسی داده‌پردازان سپهر و تسویه چندگانه',
    status: 'permanent',
    isAutoGenerated: true,
    sourceType: 'invoice',
    sourceId: 'inv-1',
    createdAt: '1403/05/12',
    items: [
      {
        id: 'vi-7',
        accountCode: '10101',
        accountTitle: 'صندوق‌ها',
        tafsiliTitle: 'صندوق مرکزی',
        description: 'دریافت نقدی وجه فاکتور ۱۰۰۱',
        debit: 14322000,
        credit: 0,
      },
      {
        id: 'vi-8',
        accountCode: '10102',
        accountTitle: 'حساب‌های بانکی ریالی',
        tafsiliTitle: 'بانک ملت ونک',
        description: 'واریز حواله ساتنا فاکتور ۱۰۰۱',
        debit: 130000000,
        credit: 0,
      },
      {
        id: 'vi-9',
        accountCode: '10201',
        accountTitle: 'چک‌های دریافتی نزد صندوق',
        tafsiliTitle: 'چک بانک پاسارگاد ۸۴۹۲۰۱۹۴',
        description: 'دریافت چک صیادی سررسید ۱۴۰۳/۰۶/۲۰',
        debit: 100000000,
        credit: 0,
      },
      {
        id: 'vi-10',
        accountCode: '50202',
        accountTitle: 'تخفیفات نقدی اعطایی فروش',
        tafsiliTitle: 'داده‌پردازان سپهر',
        description: 'تخفیف اعطا شده پای فاکتور ۱۰۰۱',
        debit: 3980000,
        credit: 0,
      },
      {
        id: 'vi-11',
        accountCode: '50101',
        accountTitle: 'فروش کالای بازرگانی',
        tafsiliTitle: 'فروش تجهیزات دیجیتال',
        description: 'مبلغ ناخالص فروش فاکتور ۱۰۰۱',
        debit: 0,
        credit: 226000000,
      },
      {
        id: 'vi-12',
        accountCode: '30301',
        accountTitle: 'مالیات و عوارض بر ارزش افزوده پرداختنی',
        tafsiliTitle: 'ارزش افزوده ۱۰٪',
        description: 'مالیات بر ارزش افزوده فاکتور ۱۰۰۱',
        debit: 0,
        credit: 22302000,
      },
    ]
  },
  {
    id: 'vch-107',
    voucherNumber: 107,
    date: '1403/05/18',
    gregorianDate: '2024-08-08',
    description: 'ثبت فروش فاکتور شماره ۱۰۰۲ به آقای دکتر علی محمدی (کارتخوان و نسیه)',
    status: 'permanent',
    isAutoGenerated: true,
    sourceType: 'invoice',
    sourceId: 'inv-2',
    createdAt: '1403/05/18',
    items: [
      {
        id: 'vi-13',
        accountCode: '10104',
        accountTitle: 'دستگاه‌های کارتخوان (POS)',
        tafsiliTitle: 'پوز فروشگاه به پرداخت',
        description: 'تراکنش کارتخوان فاکتور ۱۰۰۲',
        debit: 68075000,
        credit: 0,
      },
      {
        id: 'vi-14',
        accountCode: '10301',
        accountTitle: 'مشتریان تجاری داخلی',
        tafsiliTitle: 'آقای دکتر علی محمدی',
        description: 'مانده نسیه فاکتور ۱۰۰۲ در حساب مشتری',
        debit: 40000000,
        credit: 0,
      },
      {
        id: 'vi-15',
        accountCode: '50101',
        accountTitle: 'فروش کالای بازرگانی',
        tafsiliTitle: 'فروش لپ‌تاپ و ماوس',
        description: 'مبلغ ناخالص فروش فاکتور ۱۰۰۲',
        debit: 0,
        credit: 98250000,
      },
      {
        id: 'vi-16',
        accountCode: '30301',
        accountTitle: 'مالیات و عوارض بر ارزش افزوده پرداختنی',
        tafsiliTitle: 'ارزش افزوده ۱۰٪',
        description: 'مالیات ارزش افزوده فاکتور ۱۰۰۲',
        debit: 0,
        credit: 9825000,
      },
    ]
  }
];
